set-option -g default-terminal screen-256color

bind r source-file ~/.tmux.conf

# DESIGN TWEAKS
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=#909090 bg=#206080'
set -g status-left ''
set -g status-left-length 50
set -g status-right '#{?client_prefix,#{prefix},''} %Y-%m-%d %a %H:%M %Z'
set -g status-right-length 50

set -g pane-border-status top
set -g pane-border-format '#[bold]#{pane_current_command}'
